# 应用服务 WEB 访问端口
server.port=8080
# THYMELEAF (ThymeleafAutoConfiguration)
# 开启模板缓存（默认值： true ）
spring.thymeleaf.cache=true
# 检查模板是否存在，然后再呈现
spring.thymeleaf.check-template=true
# 检查模板位置是否正确（默认值 :true ）
spring.thymeleaf.check-template-location=true
#Content-Type 的值（默认值： text/html ）
spring.thymeleaf.content-type=text/html
# 开启 MVC Thymeleaf 视图解析（默认值： true ）
spring.thymeleaf.enabled=true
# 模板编码
spring.thymeleaf.encoding=UTF-8
# 要被排除在解析之外的视图名称列表，⽤逗号分隔
spring.thymeleaf.excluded-view-names=
# 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
spring.thymeleaf.mode=HTML5
# 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
spring.thymeleaf.prefix=classpath:/templates/
# 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
spring.thymeleaf.suffix=.html
#????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=202321110287
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# JPA ?????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
# ????????? print?????????
logging.level.com.example.demo=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=logs


alipay.appid=9021000164675234
alipay.privateKey=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCp+3R25PMfV5mHDKDxYF+NQ7q7uazuAOF3bRSaYuIDM2DklmRVeTFh4SgzZ6KEbZi0I0jpK9NPf9NRYGN3oG+t67Z5rHRGjzPIX2BdMywUajBueGRD1ViQjxYp1/ElXYkLuAccv1eKztAcLKvTp71g2sXpSPfxZoSq4jO211EMZKvSpTGNQuHuCGZMemtbV1c3tzBY60XB5OUaH6hAmKBusbgJln3g3znOMKt/chZUUb9u6xX07QS+dYRqtPTPaoq461Wo3pHLOPrCU2DkbgRFPoOuuzePvWX2s5tRSFBpAojt3/dwvje/uRzf/7mFbJcxkqCXPcT1yQcz15mOfjLbAgMBAAECggEABn6dDI3i3Ce0rfxFifNsszELSXDmspFGDBIW3283w3eLFDDK1Jk00dCQgKZNB1JIq1lNx9rsz/TKVimgo0l1+ucuqad1Kdz+1YEPZYA3BvCnuRDQg+b640sURbUCebMBMXlujCKjbaJJQUpTplqaWcECHs+y6X5JQ14xK6M+bYK7NcULo920Y7N5pLdE6ZoucyRunzrVr7iGq0N1psfs2/RPUMdKI/O+HZ3yAtN1j/sOS9vQDgHWA/aP6vCxNGZNSDsefaZUWNEegtUVNz2koMPh4fIXxijcK8oYC4w6YWKowJZdXQyrMBoy7P8sfnZZnHzRSrAl0Xc0fiVwic89wQKBgQDdfXbeUhqQhG4T4ovDwedrSbRkiCqgtHPYgtfJq6rgTDctBBajDNykVObRkJRSIKMKkrXMM69qeZVeLq9GYyeVf/9DWa4NTbPwEKQdLfGH010V+Xt13UaGZadYDepe8tlmpBQLsHL42X0tdnC6v4qOBFvkMDOUaxS/QU6EVN0hXwKBgQDEd4GbHMIOM6LFt4njN2IDGrNHwrMOTJobvlJok4pp3AVAErpxzoBT50njqz1rhJcp7fx0GWEttumROYGTutRe4V3jnGV58etYzsLjk9exxUDZ5EfCfTyQktxu2j1weo2EGnL68Sjet+GoVohMtt7But6hdm69Dd8FJq7XJGL0BQKBgBBPXuN8NEyUE+8O7a/apYn3AXuts0XmQ+mbqPxG0ex2cFG2TVxwZAcN4XlpJiLuGFN8/jotTCuRDHjFA08xmgaeSFPTVMfSAwAYmZ00dubDn8Uwe/Dv/HOFJM+NJscbJvsx9e/ubGj6ywcAA8kctb1DgOjKy+GQCRUUYA3KmgYNAoGAZQp1LHnwz2788qR/FM1B6gjMVUar4dnBlC0gosnmcKUISjiXjLpAQ2Z7GMzTrL0nJRhRMsBuux0MKHUjz/9RA27yY4Hmqn2hpS3JC1PYpYOl46nEwiC4ij4NgjFZUcSljWAw7CAk/c4iDvpZ5OJT09ywbOfE8hP1M+f+GYWMIqUCgYEAkI6mQD/Jv4ta0AuJ8aFde70lwZcC+clKgfVcal6tGuu/jsmL/1woqv9QjWJDJLSgYfZ7JJanTX67x8ureZfVsHX3V/QLUSzjsq4bFG3ShzMMGx6Oc1wh+sh22l9rZcrcXbFpfzmgEMj0Z2TKJ0WhFUfFDp/60g4WQ+Z+F07LbM4=
alipay.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkfzJrpkgG5iYmhHXeSpRjYPpOLkz0Gs5t7zC8s5c/AFOC4cwe2OrDseR4qFrfExPrJETCfz8z8Up23V4aWgPGz28C5QRZ9vASonzPeuOJwSODDOACT21U0JDiLrIF6aKSNGI84zO5U2vyVdwF9wUkZIvlODvJgIZPnNYckUpJS8OMwdoeJb1WvgZ/6DwMpp7AysYUavNm9mkxt5SkZzCjc66I/a8/7/5jQTYLzkx/Ov6uoVYwxqCK0tZZTf/RHvhUziYLa0/050tZL4wukK3KH8/oO0QYyzR/eed9P2isbBa4rz6IoSD6JA3+AJqmUJdySW+1n2bT/gs1C5Clo4KAwIDAQAB
alipay.gateway=https://openapi-sandbox.dl.alipaydev.com/gateway.do
alipay.returnUrl=http://ecb92d6b.natappfree.cc/pay/result
alipay.notifyUrl=http://ecb92d6b.natappfree.cc/pay/notify
